version: '3.1'

services:
  db-test:
    networks:
      test: {}
    extends:
      file: docker-compose.base.yml
      service: db
  redis-test:
    networks:
      test: {}
    extends:
      file: docker-compose.base.yml
      service: redis

networks:
  test: {}