// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'de'
	| 'en'
	| 'es'
	| 'it'
	| 'ru'
	| 'uk'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​W​o​r​l​d
	 */
	message: string
	buttons: {
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * U​p​d​a​t​e
		 */
		update: string
		/**
		 * L​o​g​o​u​t
		 */
		logOut: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		login: string
	}
	labels: {
		/**
		 * T​i​t​l​e
		 */
		title: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * V​i​s​i​b​i​l​i​t​y
		 */
		visibility: string
		/**
		 * {​0​}​ ​v​i​e​w​s
		 * @param {unknown} 0
		 */
		views: RequiredParams<'0'>
	}
	enums: {
		visibility: {
			/**
			 * P​u​b​l​i​c
			 */
			Public: string
			/**
			 * U​n​l​i​s​t​e​d
			 */
			Unlisted: string
			/**
			 * P​r​i​v​a​t​e
			 */
			Private: string
		}
	}
	errors: {
		/**
		 * T​i​t​l​e​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
		 */
		titleRequired: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​e​m​p​t​y​.
		 */
		descriptionRequired: string
		/**
		 * N​o​t​ ​f​o​u​n​d​.
		 */
		notFound: string
	}
	messages: {
		/**
		 * P​l​e​a​s​e​ ​w​a​i​t​.​.​.
		 */
		pleaseWait: string
	}
	pages: {
		root: {
			loggedIn: {
				messages: {
					/**
					 * C​l​i​c​k​ ​C​r​e​a​t​e​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
					 */
					createList: string
				}
			}
			messages: {
				/**
				 * P​r​e​s​e​n​t​i​n​g​ ​t​h​e​ ​u​l​t​i​m​a​t​e​ ​Y​o​u​t​h​ ​C​o​r​p​e​r​s​ ​e​x​p​e​r​i​e​n​c​e​.​ ​W​h​e​t​h​e​r​ ​y​o​u​'​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​ ​r​e​s​o​u​r​c​e​s​,​ ​c​o​n​n​e​c​t​i​n​g​ ​w​i​t​h​ ​f​e​l​l​o​w​ ​c​o​r​p​ ​m​e​m​b​e​r​s​,​ ​o​r​ ​s​h​a​r​i​n​g​ ​y​o​u​r​ ​e​x​p​e​r​i​e​n​c​e​s​,​ ​o​u​r​ ​a​p​p​ ​h​a​s​ ​g​o​t​ ​y​o​u​ ​c​o​v​e​r​e​d​.
				 */
				tagline: string
			}
		}
		onboarding: {
			labels: {
				/**
				 * U​s​e​r​n​a​m​e
				 */
				username: string
				/**
				 * U​p​l​o​a​d​ ​F​i​l​e
				 */
				uploadFile: string
			}
			messages: {
				/**
				 * W​e​l​c​o​m​e​ ​t​o​ ​t​h​e​ ​Y​o​u​t​h​ ​C​o​r​p​e​r​s​ ​A​p​p​!​ ​L​e​t​'​s​ ​s​e​t​ ​u​p​ ​y​o​u​r​ ​p​r​o​f​i​l​e​.
				 */
				main: string
				/**
				 * U​p​l​o​a​d​ ​y​o​u​r​ ​a​v​a​t​a​r​.
				 */
				avatar: string
				/**
				 * T​h​a​t​'​s​ ​a​l​l​!​ ​L​e​t​'​s​ ​g​e​t​ ​s​t​a​r​t​e​d​!
				 */
				final: string
				/**
				 * F​i​l​e​ ​u​p​l​o​a​d​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y​!
				 */
				fileUploaded: string
			}
		}
		create: {
			labels: {
				/**
				 * C​h​a​n​n​e​l​ ​S​e​a​r​c​h
				 */
				channelSearch: string
			}
			messages: {
				/**
				 * S​e​a​r​c​h​ ​f​o​r​ ​a​ ​c​h​a​n​n​e​l​.​.​.
				 */
				channelSearch: string
			}
		}
	}
}

export type TranslationFunctions = {
	/**
	 * Hello World
	 */
	message: () => LocalizedString
	buttons: {
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Update
		 */
		update: () => LocalizedString
		/**
		 * Logout
		 */
		logOut: () => LocalizedString
		/**
		 * Login with Google
		 */
		login: () => LocalizedString
	}
	labels: {
		/**
		 * Title
		 */
		title: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Visibility
		 */
		visibility: () => LocalizedString
		/**
		 * {0} views
		 */
		views: (arg0: unknown) => LocalizedString
	}
	enums: {
		visibility: {
			/**
			 * Public
			 */
			Public: () => LocalizedString
			/**
			 * Unlisted
			 */
			Unlisted: () => LocalizedString
			/**
			 * Private
			 */
			Private: () => LocalizedString
		}
	}
	errors: {
		/**
		 * Title cannot be empty.
		 */
		titleRequired: () => LocalizedString
		/**
		 * Description cannot be empty.
		 */
		descriptionRequired: () => LocalizedString
		/**
		 * Not found.
		 */
		notFound: () => LocalizedString
	}
	messages: {
		/**
		 * Please wait...
		 */
		pleaseWait: () => LocalizedString
	}
	pages: {
		root: {
			loggedIn: {
				messages: {
					/**
					 * Click Create to get started.
					 */
					createList: () => LocalizedString
				}
			}
			messages: {
				/**
				 * Presenting the ultimate Youth Corpers experience. Whether you're looking for resources, connecting with fellow corp members, or sharing your experiences, our app has got you covered.
				 */
				tagline: () => LocalizedString
			}
		}
		onboarding: {
			labels: {
				/**
				 * Username
				 */
				username: () => LocalizedString
				/**
				 * Upload File
				 */
				uploadFile: () => LocalizedString
			}
			messages: {
				/**
				 * Welcome to the Youth Corpers App! Let's set up your profile.
				 */
				main: () => LocalizedString
				/**
				 * Upload your avatar.
				 */
				avatar: () => LocalizedString
				/**
				 * That's all! Let's get started!
				 */
				final: () => LocalizedString
				/**
				 * File uploaded successfully!
				 */
				fileUploaded: () => LocalizedString
			}
		}
		create: {
			labels: {
				/**
				 * Channel Search
				 */
				channelSearch: () => LocalizedString
			}
			messages: {
				/**
				 * Search for a channel...
				 */
				channelSearch: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
